<?xml version="1.0" encoding="utf-8"?><Database Name="A_Players" Class="DataBaseModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=A_Players;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="A_PlayersConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.players" Member="Players">
    <Type Name="Player">
      <Column Name="player_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="trainer_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="nationality" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="birth_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="weight" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>